[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/'
]
[dependencies]
forge-std = "https://github.com/foundry-rs/forge-std"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
