[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia-eth= "", arb-sepolia = ""}
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/'
]
[dependencies]
forge-std = "https://github.com/foundry-rs/forge-std"

